### ISSUE TITLE
nufft: ValueError: dimension mismatch

### ISSUE THREAD

**Issue by ibkvictor** [jyhmiinlin/pynufft#44]
Trying to use py-nufft in my ada-lanczos  back-propagation step. Please, could you assist?
Implementations of ![arXiv:1808.04580](https://arxiv.org/abs/1808.04580) and ![arXiv:1901.01484](https://arxiv.org/abs/1901.01484)

```sample code
#########################################
# import NUFFT class
from pynufft import NUFFT
# Initiate the NufftObj object
NufftObj = NUFFT()
x = np.random.rand(20, 3)
om = np.random.randn(100, 1)
Nd = (20,)
Kd = (40,)
Jd = (6,)
NufftObj.plan(om, Nd, Kd, Jd)
# correction factor
##########################################
NufftObj.adjoint(x)
##########################################
r_exp = np.complex128(np.zeros((N, N)))
for j in range(N):
    for v_i in v_features:
        r_exp[j][k] = cmath.exp(- 2 * cmath.pi * 1.j * k * v_i)

np.dot(r_exp, v_features)
##########################################
f = np.multiply(b, x)
##########################################
f_RF = NufftObj.forward(f)
##########################################
print(f"f_RF is {f_RF}")
```

error
```
Traceback (most recent call last):
  File "/Users/victorezekiel/Downloads/NFFT-Lanczos-Example-v1/fft.py", line 42, in <module>
    NufftObj.adjoint(x)
  File "/Users/victorezekiel/.local/lib/python3.9/site-packages/pynufft/nufft/__init__.py", line 625, in adjoint
    return func.get(self.processor)(*args, **kwargs)
  File "/Users/victorezekiel/.local/lib/python3.9/site-packages/pynufft/nufft/_nufft_class_methods_cpu.py", line 191, in _adjoint_cpu
    x = self._xx2x_cpu(self._k2xx_cpu(self._y2k_cpu(y)))
  File "/Users/victorezekiel/.local/lib/python3.9/site-packages/pynufft/nufft/_nufft_class_methods_cpu.py", line 312, in _y2k_cpu
    k_vec = self._y2vec_cpu(y)
  File "/Users/victorezekiel/.local/lib/python3.9/site-packages/pynufft/nufft/_nufft_class_methods_cpu.py", line 295, in _y2vec_cpu
    k_vec = self.spH.dot(y)
  File "/opt/miniconda3/lib/python3.9/site-packages/scipy/sparse/_base.py", line 416, in dot
    return self @ other
  File "/opt/miniconda3/lib/python3.9/site-packages/scipy/sparse/_base.py", line 630, in __matmul__
    return self._mul_dispatch(other)
  File "/opt/miniconda3/lib/python3.9/site-packages/scipy/sparse/_base.py", line 577, in _mul_dispatch
```

**Comment by jyhmiinlin** [comment]
I cannot run the above script. It skips some lines (the np was not imported). 

However, I thought it failed at the line "NufftObj.adjoint(x)". 
Here, the variable of adjoint() should be a vector with a shape of (100, ).

**Comment by ibkvictor** [comment]
Thank you Jyh-Miin Lin,

I have actually figure that out just a few moments before your message. I am very grateful for your response. Please, I would like to your opinion on my project. I am using nufft to accelerate my gnn training. However, I keep getting a complex number after the adjoint, matmul, and forward operation. Do you have an Idea of what I might be doing wrong.

Here is a bit of the pipeline: 
The adjacency matrix, i.e edge weights, is modeled as an MLP output to gaussian kernel same as Ada-lanczosnet. Then, eigen-value computation for filtering signal. The eigen-value computation is where I use the lanczos method and your nufft framework. Thanks in advance for any help.

Sincerely,
Victor Ezekiel.

**Comment by jyhmiinlin** [comment]
Thanks. Yes, forward and adjoint always give complex values because of the nature of the discrete Fourier transform.

If complex values are annoying, you could try to cast the variable using numpy's astype(). 

For example, arr.astype(numpy.float32) can drop imaginary part of arr.
